### ISSUE TITLE
ListItems is not working as expected

### ISSUE THREAD

**Issue by prateekrastogi** [recombee/node-api-client#1]
Hi,
I am trying to use the nodeclient to get the of all the items uploaded to the recombee. For doing so, I am calling rqs ListItems method without passing any optional filter parameter but I am not getting the list of all the items as expected. Here, is my code `  recombeeClient.send(new recombeeRqs.ListItems(), (err, result) => {
      console.log(err)
      console.log(result)
    }`

**Comment by OndraFiedler** [comment]
Hi,
if I try: `recombeeClient.send(new recombeeRqs.ListItems(), (err, result) => {console.log(err); console.log(result); });` then it works for me and returns items.
Is it possible that the problem is only in missing semicolon after `console.log(err)`?

**Comment by prateekrastogi** [comment]
Yeah, it's working with semicolon. Also, right now it started working without semi colons too. May be at that time my db was just initalized and seeded with little amount of data, which may have given rise to that issue. 
Also, i am unable to bind recombee api function calls with rxjs using rxjs 'bindNodeCallback' method, but binding is successful using rxjs 'fromPromise' method. Ideally, both ways of bindings should work flawless as lib supports both callback and promises. If you are interested in the issue, and got little idea about rxjs in general, I can open a issue to elaborate that problem.

**Comment by OndraFiedler** [comment]
Thanks for checking that it works :) There could also be some delay between sending the data and showing up of items in the result of ListItems, as this endpoint currently reads data from a queued backend database.

Regarding rxjs: Please open the issue, I will check what is wrong. Thanks!
