### ISSUE TITLE
`cls-bluebird` dependency problem when using Webpack

### ISSUE THREAD

**Issue by yoadsn** [recombee/node-api-client#10]
Hi,
We use Webpack to bundle our server-side code.
At the moment, the version of `request-promise` used by this SDK is 3 which has a problem with a dependency on `cls-bluebird`.
The error we get from the bundler is:
```
ERROR in ./node_modules/request-promise/lib/rp.js
Module not found: Error: Can't resolve 'cls-bluebird' in '/Users/--/--/node_modules/request-promise/lib'
```

This issue:
https://github.com/request/request-promise/issues/91
Describes the cause, a workaround and a final fix in the 4 version of `request-promise`.

Are you able to upgrade the dependency to version 4 and resolve this problem?

**Comment by OndraFiedler** [comment]
Thanks for letting us know about the issue.
`request-promise` has been upgraded to version 4 in the latest release (https://github.com/recombee/node-api-client/releases/tag/v2.4.1).
