### ISSUE TITLE
DeleteRating gives 404

### ISSUE THREAD

**Issue by agyimr** [recombee/node-api-client#14]
Hi!

I have been trying to delete a rating through the node client, and always end up getting a 404 error. I reached a point, where I believe there might be an issue on the backend. Could you look into it?

When a rating is created I attach the timestamp to it, upon deletion, I leave the timestamp out. According to the docs, I expect the system to delete all of the ratings with userId and itemId. But I end up getting a 404. 

Here is the code I use to delete the rating:

`

    console.log(DATABASE_NAME);
    console.log(userId);
    console.log(itemId);
    // tslint:disable-next-line
    await client.send(new rqs.DeleteRating(userId, itemId));

`

Here is the error I get, upon invoking this function.

`
binge-trade-dev
qAyX7PsaIybRlE5Hr7UlVcRi1Hb2
a9ba7ce8-b067-4a7f-b6ce-6f547ab659ec

ResponseError: 404 - {"message":"Rating of userId=\"qAyX7PsaIybRlE5Hr7UlVcRi1Hb2\",itemId=\"a9ba7ce8-b067-4a7f-b6ce-6f547ab659ec\" does not exist!"}
    at rp.then.then.catch (/workspace/node_modules/recombee-api-client/lib/api-client.js:68:23)
    at tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23) 
`

And here is a screenshot taken from the Recombee admin console, verifying that the rating in question does indeed exist.

![error](https://user-images.githubusercontent.com/23366539/96707052-aab65e80-1397-11eb-8bba-6f0672495161.png)

**Comment by DanielBreiner** [comment]
Sorry for not getting back to you sooner. I will close this issue for inactivity, if the problem persists, feel free to reopen it or create a new one.
