### ISSUE TITLE
Unable to set custom timeout per request

### ISSUE THREAD

**Issue by MonsterDeveloper** [recombee/node-api-client#15]
Hi. How can I set custom timeout per request in this client? I need to set more than 3000 ms timeout for the RecommendItemsToUser request, but it seems to me that it is hard-coded:

node-api-client/lib/requests/recommend-items-to-user.js
```js
super('POST', `/recomms/users/${userId}/items/`, 3000, false);
```

**Comment by OndraFiedler** [comment]
You can directly set the timeout property:
```node

    let req = new rqs.RecommendItemsToUser('user-1', 5);
    req.timeout = 10000;
```
