### ISSUE TITLE
api client callbacks not properly binding with rxjs 

### ISSUE THREAD

**Issue by prateekrastogi** [recombee/node-api-client#2]
Rxjs allows to convert node callbacks functions to observables using bindNodeCallback [http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-bindNodeCallback](url) . It also allows to convert js promises to observable using [http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-fromPromise](url) . As the recombee client library supports both promises and callback. Here are two alternative approaches to get an Observable from recombee api call:
`Rx.Observable.fromPromise(client.send(new rqs.ListItems()))  or
const RecombeeClient = Rx.Observable.bindNodeCallback(client.send) ,thereafter,
RecombeeClient(new rqs.ListItems())`
If we are doing similiar calls in large no. then the first approach get slightly lengthy to type such as in the case of adding multiple item properties. Also, ideally as recombee client api supports node callback style functions it should work properly. What could be possible reason? I think the need for construction of new request object while calling callback might be somehow related to the issue. Thanks.

**Comment by OndraFiedler** [comment]
Thanks for opening the task. What does the failing approach produce? Does it throw an exception?

**Comment by prateekrastogi** [comment]
It fails silently no error and no result. Sort of nothing

**Comment by OndraFiedler** [comment]
I think the problem might be, that the `client` object is not bind to the `client.send` method.
(same issue as https://github.com/ReactiveX/rxjs/issues/1720).

The following code works for me:
```javascript
var clientSendAsObservable = Rx.Observable.bindNodeCallback(client.send.bind(client));
var result = clientSendAsObservable(new rqs.ListItems());
result.subscribe(x => console.log(x), e => console.error(e));
```


Does this solve your problem?

**Comment by prateekrastogi** [comment]
Hi,
Now, its working properly. Thanks a lot. You saved me lots of boring keystrokes.
