### ISSUE TITLE
How to set values of itemproperty of type 'set'?

### ISSUE THREAD

**Issue by prateekrastogi** [recombee/node-api-client#3]
Hi,
I have an array which i converted to set object using new Set(array) method of javascript. Now, such set objects are values of keys of a json object, which i pass in to recombeeclient's  rqs.SetItemValues(id, json object) method  with cascadecreate: true set. But, what actually is happening is that cascadecreate creates a new null object but the type conversion of json object to recombee's internal type system fails. Thus, creating the right no. of null objects i.e. objects with id set and all the fields are null. This, only happens when i try to set the values of ''set' type item properties', if i leave them, or remove them, i am successfully able to create item with remaining fields in recombee db storage. 
Please tell me correct way of setting 'set' item properties. Also, you can update the documentation too, to include that case.

**Comment by OndraFiedler** [comment]
Hi,
could you please provide some sample code which produces the issue?
An example of how to set properties (including a property of type set) is in Getting started: https://docs.recombee.com/gettingstarted.html#sending-item-values .

**Comment by prateekrastogi** [comment]
Hi,
I think I have reached the root of the problem. Assume a json object, let's call is x, Now,:
id of x is id, and,
x.a = ["d","f","g"]
x.b = [1,2,3]

Now, as per as recombee guide for uploading this itemtype both x.a and x.b should be of itemtype set.
Now using new recombeeRqs.SetItemValues(id, x, {'cascadeCreate': true}). Now, as per as doc we should get this item seeded in recombee with fields  a being a set of strings and b being set of numbers.  But, what actually is happening is that cascade create is creating a null object of passed id.
So, when we seed a modified x item with the only field x.a = arr[string], then your setitemvalues method is working perfectly fine in uplkoading the item and setting its value. But, as soon as we include field b of itemtype set and pass it an array of integers, assuming it would create set of number on recombee's backend, we are starting to failed uploads with null object of id passed created.
So, i guess my issue boils down to failure in uploading a number set as an array of integers.

**Comment by OndraFiedler** [comment]
We support only set of strings (this should be probably more emphasized in the documentation), so setting `[1,2,3]` should give `HTTP 400 Bad Request`.

When I try:
```js
client.send(new rqs.Batch([new rqs.ResetDatabase(),
    new rqs.AddItemProperty('setprop', 'set'),
  ]))
  .then((responses) => {
    var request = new rqs.SetItemValues(
        `item1`, //itemId
        //values:
        {
          'setprop': [1,2,3]
        },
        {
          'cascadeCreate': true 
        }
      );
    return client.send(request);
  })
  .then((response) => {
    console.log(response);
  })
  .catch((error) => {
    console.error(error);
  });
```
I get `HTTP 400` with message `Invalid value for property "setprop" of type set. Set should be given as a JSON array of strings!` and the item is not created (which is correct behavior). Can you please give an example when the request with set of numbers succeed or the item is created?

I suggest to send the string representations of the numbers.

**Comment by OndraFiedler** [comment]
Sorry, I must have somehow overlooked it - the request returned `HTTP 400` (correct) but the item really got created, which I think is not correct. I have created a ticket in our bug tracker in order to fix this issue in the API.

**Comment by prateekrastogi** [comment]
Hi,
If you only support set of strings, then according to https://docs.recombee.com/reql_values_operators.html#sets how do you support set of numbers given in the docs?
Also, I have not yet created any successful request to set the set of integers.

**Comment by OndraFiedler** [comment]
> according to https://docs.recombee.com/reql_values_operators.html#sets how do you support set of numbers

You can use set of numbers in the [ReQL filters](https://docs.recombee.com/reql_filtering_and_boosting.html). For example if you have property `int_prop` of type int, then you can use ReQL expression `'int_prop' in {1,42,99}`, to test whether `int_prop` equals to any of the numbers.
If you really need to use the values of a set property as numbers in the filter, you can convert them from strings to numbers using `map(lambda 'x': number('x'), 'set_prop')`. But in most cases this is not necessary.

**Comment by prateekrastogi** [comment]
Fine, I guess I have to do type conversion in ReQL then. Thank you.
