### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by prateekrastogi** [recombee/node-api-client#4]
Hi,

While trying to use api client in my code I am getting the following error:

{ ResponseError: 401 - {"statusCode":401,"error":"Token has expired (Current time: 1516621614 or 2018-01-22 11:46:54 UTC, you are 42s off)"}
    at rp.then.then.catch (C:\Code\seeder\node_modules\recombee-api-client\lib\api-client.js:68:23)

I have tried running the request multiple times and every time i am getting the same 42s delay 401 auth error.

**Comment by OndraFiedler** [comment]
Most probably the time on your machine is out of sync. It is used in the authentication, and if it is not synchronized, the authentication fails, request is refused by the API and you get the error you mention.
Can you please check whether it is synchronized?

**Comment by prateekrastogi** [comment]
Syncing time appropriately solved the issue. Thanks. Btw, how much time drift is permissible for api requests?

**Comment by OndraFiedler** [comment]
I think there is a 10 seconds time window.

**Comment by prateekrastogi** [comment]
Hi,
Is there any other workaround for the issue? It seems that my computer's time is being set by my organization internal time server with no option to turn that off, and all the workarounds to reduce time drift end up being temporary.

Thanks.

**Comment by OndraFiedler** [comment]
It is not possible to authenticate without synchronized time. So you probably need to report to your organization, that the time server is delayed.

**Comment by prateekrastogi** [comment]
Thanks. Although, I already did informed them, but the size and layers of red tape will make the whole process quite sluggish and cumbersome. So, I was looking for a quick fix. Anyway, thanks for clarifying.
