### ISSUE TITLE
Feature request: Add http(s).Agent for request

### ISSUE THREAD

**Issue by Goues** [recombee/node-api-client#6]
At the moment, the client only allows to set a `proxy` for request library in the constructor. We would like add an Agent to make use of keep-alive.

Please add support for `agent` in client options to be aplied for requests such as:
```
const agent = new http(s).Agent({
    keepAlive: true
});

const client = new ApiClient(__user__, __apiKey__, __https__, { agent });
```

Alternatively, allow sending the `forever` option of request.

**Comment by vallpaper** [comment]
Resolved in https://github.com/recombee/node-api-client/pull/20
