### ISSUE TITLE
Feature request: OAuth integration

### ISSUE THREAD

**Issue by ridhwaans** [recombee/node-api-client#7]
The client requests currently specify the api key as a query param, but a lot of services like spotify, google, and facebook use oauth with client id and secret key for access tokens before request.

**Comment by OndraFiedler** [comment]
What do you need it for? Recombee is designed for handling high traffic and therefore use HMAC request signing which can be resolved very fast.

**Comment by ridhwaans** [comment]
My use cases require me to a hit a spotify endpoint for music metadata, which requires preauthentication with an access token ( i.e. `headers['Authorization'] = 'Bearer ' + this.accessToken`)
(the service authorization is outlined here https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-flows)  

It will be invaluable if there is a distinction between oauth and non-oauth services in the `node-api-client`

**Comment by DanielBreiner** [comment]
Sorry for not getting back to you sooner. I will close this issue for inactivity, if the problem persists, feel free to reopen it or create a new one.
